plugin: netbox.netbox.nb_inventory

api_endpoint: http://192.168.201.136:8000

token:
  type: Bearer
  value: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

validate_certs: false
config_context: false

device_query_filters:
  - has_primary_ip: "true"

groups:
  cisco_routers: "platform.slug == 'cisco-ios-xe'"

compose:
  ansible_connection: "'ansible.netcommon.network_cli'"
  ansible_network_os: "'cisco.ios.ios'"
  ansible_user: "'automation'"