# strongSwan branch-side reference used in the lab.
# Lab addressing only. Do not publish real PSKs.
# IMPORTANT: DES was used only because the FortiGate EVAL image exposed low-encryption proposals.
# Production deployments should use modern AES-based cryptography.

config setup
    charondebug="ike 2, knl 2, cfg 2"

conn HQ-BRANCH-WAN1
    keyexchange=ikev2

    left=192.168.201.134
    leftid=192.168.201.134
    leftsubnet=10.20.20.0/24

    right=192.168.201.132
    rightid=192.168.201.132
    rightsubnet=10.10.10.0/24

    authby=psk
    ike=des-sha256-modp2048!
    esp=des-sha256-modp2048!

    type=tunnel
    auto=add

# /etc/ipsec.secrets example:
# 192.168.201.134 192.168.201.132 : PSK "<REDACTED>"
