hostname R1
ip route 100.100.100.100/32 Null0
interface eth0
 ip address 10.0.12.1/30
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 <REDACTED>
 ip ospf network point-to-point
interface eth1
 ip address 10.0.13.1/30
 ip ospf cost 30
 ip ospf network point-to-point
interface lo
 ip address 1.1.1.1/32
router ospf
 ospf router-id 1.1.1.1
 redistribute static metric 20
 network 1.1.1.1/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.13.0/30 area 0
