hostname R2
interface eth0
 ip address 10.0.12.2/30
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 <REDACTED>
 ip ospf network point-to-point
interface eth1
 ip address 10.0.23.1/30
interface lo
 ip address 2.2.2.2/32
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.23.0/30 area 0
