hostname R3
interface eth0
 ip address 10.0.23.2/30
interface eth1
 ip address 10.0.13.2/30
 ip ospf network point-to-point
interface eth2
 ip address 10.0.34.1/30
 ip ospf network point-to-point
interface lo
 ip address 3.3.3.3/32
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0
 network 10.0.13.0/30 area 0
 network 10.0.23.0/30 area 0
 network 10.0.34.0/30 area 1
 area 1 nssa no-summary
 area 1 range 172.168.1.0/29
