interface=wlan0
driver=nl80211
bridge=br0
ssid=CORP-WIFI
channel=6
beacon_int=1000
auth_algs=1
ieee8021x=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
own_ip_addr=10.10.99.10
nas_identifier=CORP-AP
auth_server_addr=10.10.99.20
auth_server_port=1812
auth_server_shared_secret=CorpAPRadius2026Key
acct_server_addr=10.10.99.20
acct_server_port=1813
acct_server_shared_secret=CorpAPRadius2026Key
ctrl_interface=/var/run/hostapd

# RADIUS Dynamic Authorization / CoA
radius_das_port=3799
radius_das_client=10.10.99.20 CorpAPDas2026
radius_das_time_window=300
radius_das_require_event_timestamp=0
