interface=wlan0
driver=nl80211
bridge=br0
ssid=GUEST-WIFI
channel=6
beacon_int=1000
auth_algs=1
wpa=0
ctrl_interface=/var/run/hostapd

# Lab note:
# Guest was intentionally open to focus on segmentation policy.
# Production guest WLAN may use captive portal, OWE, credentials, or other policy.
