ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="CORP-WIFI"
    key_mgmt=WPA-EAP
    eap=TLS
    identity="corp-client"
    ca_cert="/home/cisco/eap-tls/ca.crt"
    client_cert="/home/cisco/eap-tls/corp-client.crt"
    private_key="/home/cisco/eap-tls/corp-client.key"
    domain_match="RADIUS1"
}
